server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true
  client:
    default-config: default
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: Full
      dev:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: HEADERS
spring:
  application:
    name: cloud-consumer-feign-hystrix-order

logging:
  level:
    com.czp.springcloud.feign.PaymentHystrixService: debug