server:
  port: 9003

spring:
  application:
    name: cloud-alibaba-nacos-ribbon-client
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
