server:
  port: 9510

spring:
  application:
    name: cloud-gateway-dynamic-route-server-9510

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hoxton2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 742003942
  cloud:
    gateway:
      set-status:
        original-status-header-name: original-http-status
      enabled: true
      discovery:
        locator:
          enabled: true

  boot:
    admin:
      client:
        url: http://localhost:8769
        instance:
          name: ${spring.application.name}
          metadata:
            user.name: czp
            user.password: 742003942

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    check-template: false
    check-template-location: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug
    de.codecentric.boot.admin.client: debug
    org.springframework.web: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.czp.springcloud.entity
  configuration:
    map-underscore-to-camel-case: true