server:
  port: 7001


spring:
  application:
    name: cloud-eureka-server-7001

eureka:
  instance:
    hostname: eureka7001.com
    prefer-ip-address: true
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS