server:
  port: 85
spring:
  application:
    name: cloud-alibaba-consumer-nacos-openfeign-order-85
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: '*'


#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
